job('First-Maven-Project-Via-DSL'){
	description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven Project hosted on github")
	scm {
		git("https://github.com/sudhansu133/Git_Training_t3.git", master)
	}
	triggers {
		scm('* * * * *')
	}
	stpes {
		maven('clean package', 'pom.xml')
	}
	publishers {
		archiveArtifacts '**/*.war'
	}
} 
